COLOR_NORMALIZATION_FACTOR: 255.0 # For uint8 images
COLOR_DATA_TYPE: "uint8" # If altered, include changes in the code
COLOR_ENCODING: 'rgb8'
COLOR_CHANNELS: 3

DEPTH_NORMALIZATION_FACTOR: 65535.0 # For uint16 images
DEPTH_DATA_TYPE: "uint16" # If alterend, include changes in the code
DEPTH_ENCODING: 'mono16'
DEPTH_CHANNELS: 1

BATCH_SIZE: 1
OUTPUT_SHAPE: "12" # (1,2)
COLOR_INPUT_IDX: 0 # TODO
DEPTH_INPUT_IDX: 0 # TODO
OUTPUT_IDX: 2 # TODO

