

teleop_twist_joy_node:
  ros__parameters:
    # Linear axes for forward/backward motion
    axis_linear:
      x: 1  # Left stick Y-axis (adjust based on your joystick mapping)
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 1.5

    # Angular axis for left/right rotation
    axis_angular:
      yaw: 2  # Right stick X-axis (adjust based on your joystick mapping)
    scale_angular:
      yaw: 0.6
    scale_angular_turbo:
      yaw: 0.8

    # Button configuration
    require_enable_button: false
    # enable_button: 3           # Enable/disable teleop control (e.g., trigger button)
    # enable_turbo_button: 5      # Turbo mode button (optional, e.g., button 2)
    # autorepeat_rate: 30
