
camera_name: "realsense_d455"
enable_color: true
enable_depth: true
gyro_fps: 150  # Explicitly set FPS
accel_fps: 150  # Explicitly set FPS
color_width: 640
color_height: 480
color_fps: 30
depth_width: 640
depth_height: 480
depth_fps: 30
align_depth: true
enable_pointcloud: true
