site_name: Robot Jeteja Documentation
site_url: https://AshtonJohns.github.io/UCAJetson/
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Bill of Materials: BOM.md
  - Resources: Resources.md
  # - API Reference: api.md

theme:
  name: readthedocs
